language: node_js
node_js:
    - "10"
    - "12"
    - "14"

before_install:
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.2-amd64.deb | sudo dpkg -i --force-confnew -
  - sudo service elasticsearch restart

services:
# https://docs.travis-ci.com/user/database-setup/
   - elasticsearch
#  - mongodb
#  - redis-server

before_script:

script:
    - npm run lint
    - npm test

after_success:

# enable codecov, which doesn't currently work for plugins because
# plugins are run in vm.runInNewContext()
#
#   - npm install istanbul codecov
#   - npm run cover
#   - ./node_modules/.bin/codecov

sudo: false
