language: node_js
node_js:
    - "10"
    - "12"
    - "14"

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.8.deb && sudo dpkg -i --force-confnew elasticsearch-6.8.8.deb && sudo service elasticsearch restart

services:
# https://docs.travis-ci.com/user/database-setup/
   - elasticsearch

before_script:

script:
    - npm run lint
    - npm test

after_success:

sudo: false
