environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - choco install elasticsearch --version 2.3.1 -i
  - npm install

before_build:
build: off
after_build:

before_test:
  - node --version
  - npm --version

test_script:
  - npm test

after_test:

