name: Unit Tests

on: [ push, pull_request ]

jobs:

  ci-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [10.x, 12.x, 14.x]
      fail-fast: false

    steps:

    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - uses: miyataka/elasticsearch-github-actions@1
      with:
        stack-version: '6.8.8'

    - uses: actions/checkout@v1
      name: Checkout project
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v1
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: npm install

    - name: Run test suite
      run: npm run test

      env:
        CI: true
