on: [ pull_request ]

name: Test Coverage

jobs:

  coverage:
    name: Codecov
    runs-on: ubuntu-latest

    steps:

    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - uses: miyataka/elasticsearch-github-actions@1
      with:
        stack-version: '6.8.8'

    - uses: actions/checkout@master
      name: Checkout
      with:
        fetch-depth: 1

    - name: Use Node.js 10
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: install, run
      run: |
        npm install
        npm install --no-save nyc codecov
        npm run cover

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
